language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"

install:
  - pip install -U pip
  - pip install -r requirements_test.txt
  - pip install $DJANGO

script:
  - python runtests.py

matrix:
  exclude:
  - env: DJANGO="Django<1.10"
    python: "3.3"
